#+TITLE: Emacs init startup

* Directories

  These are the directories commonly used in startup scripts.

  - ~my-confdir~ refers to the directory in which emacs initialization
    starts.
  - ~my-init-dir~ is the directory in which the initialization modules
    are defined.

    #+BEGIN_SRC emacs-lisp
      (defconst my-confdir (file-name-directory (or buffer-file-name load-file-name)))
      (defconst my-init-dir (concat my-confdir "init/"))
    #+END_SRC

* Initialisation modules

   I split my configuration in different modules so that I can enable /
   disable one at will.

   A module is either a =*.el= or =*.org= file placed in ~my-init-dir~.

** Modules listing

   These are all the modules. The modules with checked boxes will be
   loaded.

   #+name: modules-list
   - [X] custom
   - [X] package
   - [X] theme
   - [X] ergo
   - [X] helm
   - [X] cedet
   - [X] jabber
   - [X] gtags
   - [X] flycheck
   - [X] company
   - [X] project
   - [X] eldoc
   - [ ] typescript
   - [X] web
   - [X] clojure
   - [X] lisp
   - [X] tlsd
   - [X] haskell
   - [ ] mu4e
   - [ ] redmine
   - [X] local

   These modules will be registered in ~my-enabled-modules~.

   #+BEGIN_SRC emacs-lisp
     (defconst my-enabled-modules '())
   #+END_SRC

   This piece of code extracts the enabled modules from the list and
   put them in the ~my-enabled-modules~ variable.

   #+BEGIN_SRC emacs-lisp :var modules-list=modules-list
     (dolist (item modules-list)
       (when (equal (string-match (rx "[CBON] ") item) 0)
         (push (substring item 7) my-enabled-modules)))

     (setq my-enabled-modules (reverse my-enabled-modules))
   #+END_SRC

** Loading modules

   This function loads the compiled Emacs lisp for the provided module.

   #+BEGIN_SRC emacs-lisp
     (defun my-load-module (module)
       (load (concat my-init-dir module)))
   #+END_SRC

   With the previous helper functions, the code to load each enabled
   modules is pretty straightforward:

   #+BEGIN_SRC emacs-lisp
     (mapc #'my-load-module my-enabled-modules)
   #+END_SRC

* Compilation

  In order to avoid loading Org on initialization, I compile Org
  sources to Emacs lisp bytecode. This has been inspired by [[https://ryuslash.org/dotfiles/emacs/init.html][this nice
  emacs conf]]. Here is the makefile :

  #+BEGIN_SRC makefile :tangle Makefile
MODULES = $(wildcard init/*.org)

init.el: init.org
	emacs -Q -batch -l "ob-tangle" -eval "(progn (setq org-src-preserve-indentation t) (org-babel-tangle-file \"$<\" \"$(notdir $@)\"))"

init/%.el: init/%.org
	emacs -Q -batch -l "ob-tangle" -eval "(org-babel-tangle-file \"$<\" \"$(notdir $@)\")"

%.elc: %.el
	emacs -Q -batch -eval "(byte-compile-file \"$<\")"

all: init.elc $(MODULES:.org=.elc)
  #+END_SRC

  To launch compilation from Emacs, use this function:

  #+BEGIN_SRC emacs-lisp
    (defun my-compile-init-files ()
      (interactive)
      (let ((default-directory my-confdir))
        (async-shell-command "make all")))
  #+END_SRC

# Local Variables:
# org-src-preserve-indentation: t
# End:
